"""empty message

Revision ID: 69940b6c5a1e
Revises: d62db988281a
Create Date: 2018-05-16 22:21:17.804215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69940b6c5a1e'
down_revision = 'd62db988281a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_name', sa.String(length=50), nullable=False),
    sa.Column('good_desc', sa.String(length=200), nullable=False),
    sa.Column('picture_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
